//! An epub flattened into one plain-text string.
//!
//! For reading paper: the epub of a book being read on paper is the only way
//! to get the *text* of the pages turned, and the only thing that has to
//! survive is the reading order and the characters. So this keeps the spine
//! order and throws away everything else — no chapters, no headings, no
//! structure of any kind.
//!
//! **Ruby is dropped, and that is the point.** `<rt>` holds a reading the
//! printed page shows above the kanji, not text that was read as text.
//! Keeping it would put かんじ into the line right after 漢字 and the
//! tokenizer would make a word of it.
//!
//! The markup is stripped by hand rather than parsed as XML. Epub XHTML is
//! generated by a hundred different tools and a strict parser gives up on
//! files that render perfectly well everywhere; there is nothing here that
//! needs a tree.

use std::collections::HashMap;
use std::io::{Cursor, Read};

#[derive(Debug, thiserror::Error)]
pub enum EpubError {
    #[error("not a readable zip: {0}")]
    Zip(#[from] zip::result::ZipError),
    #[error("io: {0}")]
    Io(#[from] std::io::Error),
    #[error("no readable text in the epub")]
    Empty,
}

/// Every document in the spine, in reading order, as text.
pub fn flatten(bytes: &[u8]) -> Result<String, EpubError> {
    let mut zip = zip::ZipArchive::new(Cursor::new(bytes))?;
    let names: Vec<String> = (0..zip.len())
        .filter_map(|i| zip.by_index(i).ok().map(|f| f.name().to_string()))
        .collect();

    let order = spine_order(&mut zip, &names).unwrap_or_else(|| fallback_order(&names));

    let mut out = String::new();
    for name in order {
        let Some(raw) = read_entry(&mut zip, &name) else {
            continue;
        };
        let text = strip_markup(&raw);
        if text.trim().is_empty() {
            continue;
        }
        if !out.is_empty() {
            out.push('\n');
        }
        out.push_str(text.trim());
    }
    if out.trim().is_empty() {
        return Err(EpubError::Empty);
    }
    Ok(out)
}

fn read_entry(zip: &mut zip::ZipArchive<Cursor<&[u8]>>, name: &str) -> Option<String> {
    // from_utf8_lossy rather than a hard failure: one document with a bad byte
    // must not cost the whole book.
    read_bytes(zip, name).map(|b| String::from_utf8_lossy(&b).into_owned())
}

fn read_bytes(zip: &mut zip::ZipArchive<Cursor<&[u8]>>, name: &str) -> Option<Vec<u8>> {
    let mut f = zip.by_name(name).ok()?;
    let mut buf = Vec::new();
    f.read_to_end(&mut buf).ok()?;
    Some(buf)
}

/// The book's cover art, for the shelf.
///
/// Best effort by design: a book with no findable cover is a book without one,
/// never a failed import.
pub struct Cover {
    pub bytes: Vec<u8>,
    /// Lowercased, from the filename — what the served file is named with.
    pub ext: String,
}

pub fn cover(bytes: &[u8]) -> Option<Cover> {
    let mut zip = zip::ZipArchive::new(Cursor::new(bytes)).ok()?;
    let names: Vec<String> = (0..zip.len())
        .filter_map(|i| zip.by_index(i).ok().map(|f| f.name().to_string()))
        .collect();
    let href = declared_cover(&mut zip, &names).or_else(|| guessed_cover(&names))?;
    let ext = href
        .rsplit('.')
        .next()
        .filter(|e| e.len() <= 4 && e.chars().all(|c| c.is_ascii_alphanumeric()))
        .unwrap_or("jpg")
        .to_ascii_lowercase();
    Some(Cover {
        bytes: read_bytes(&mut zip, &href)?,
        ext,
    })
}

/// The cover the OPF names. Two spellings, because epub 3 replaced epub 2's
/// without anything dropping the old one: a manifest item carrying the
/// `cover-image` property, or a `<meta name="cover">` pointing at an item id.
fn declared_cover(zip: &mut zip::ZipArchive<Cursor<&[u8]>>, names: &[String]) -> Option<String> {
    let container = read_entry(zip, "META-INF/container.xml")?;
    let opf_path = attr_of(&container, "rootfile", "full-path")?;
    let opf = read_entry(zip, &opf_path)?;
    let base = opf_path.rsplit_once('/').map(|(dir, _)| dir).unwrap_or("");

    let items = tags_named(&opf, "item");
    let by_property = items.iter().find(|t| {
        attr(t, "properties").is_some_and(|p| p.split_whitespace().any(|w| w == "cover-image"))
    });
    let by_meta = || {
        let id = tags_named(&opf, "meta")
            .iter()
            .find(|t| attr(t, "name").is_some_and(|n| n.eq_ignore_ascii_case("cover")))
            .and_then(|t| attr(t, "content"))?;
        items.iter().find(|t| attr(t, "id").as_deref() == Some(&id))
    };
    let href = by_property.or_else(by_meta).and_then(|t| attr(t, "href"))?;
    let path = resolve(base, &href);
    names.contains(&path).then_some(path)
}

/// What is left when the OPF names nothing: an image file that says it is the
/// cover. The shortest name wins, so `cover.jpg` beats `cover-thumbnail.jpg`.
fn guessed_cover(names: &[String]) -> Option<String> {
    names
        .iter()
        .filter(|n| {
            let lower = n.to_ascii_lowercase();
            lower.contains("cover")
                && [".jpg", ".jpeg", ".png", ".gif", ".webp"]
                    .iter()
                    .any(|e| lower.ends_with(e))
        })
        .min_by_key(|n| n.len())
        .cloned()
}

/// The spine, resolved through `container.xml` and the OPF. `None` when either
/// is missing or says nothing usable.
fn spine_order(zip: &mut zip::ZipArchive<Cursor<&[u8]>>, names: &[String]) -> Option<Vec<String>> {
    let container = read_entry(zip, "META-INF/container.xml")?;
    let opf_path = attr_of(&container, "rootfile", "full-path")?;
    let opf = read_entry(zip, &opf_path)?;
    let base = opf_path.rsplit_once('/').map(|(dir, _)| dir).unwrap_or("");

    let mut manifest: HashMap<String, String> = HashMap::new();
    for tag in tags_named(&opf, "item") {
        if let (Some(id), Some(href)) = (attr(&tag, "id"), attr(&tag, "href")) {
            manifest.insert(id, href);
        }
    }
    let order: Vec<String> = tags_named(&opf, "itemref")
        .iter()
        .filter_map(|t| attr(t, "idref"))
        .filter_map(|id| manifest.get(&id).cloned())
        .map(|href| resolve(base, &href))
        // A spine entry whose file is not in the zip is skipped rather than
        // fatal — the rest of the book is still the book.
        .filter(|p| names.iter().any(|n| n == p))
        .collect();
    (!order.is_empty()).then_some(order)
}

/// Every XHTML document in the zip, by name. What is left when there is no
/// usable spine: alphabetical order is what epub filenames are built for.
fn fallback_order(names: &[String]) -> Vec<String> {
    let mut docs: Vec<String> = names
        .iter()
        .filter(|n| {
            let lower = n.to_ascii_lowercase();
            lower.ends_with(".xhtml") || lower.ends_with(".html") || lower.ends_with(".htm")
        })
        .cloned()
        .collect();
    docs.sort();
    docs
}

/// Join an OPF-relative href to the OPF's own directory, resolving `../`.
fn resolve(base: &str, href: &str) -> String {
    let href = href.split(['#', '?']).next().unwrap_or(href);
    let mut parts: Vec<&str> = if base.is_empty() {
        Vec::new()
    } else {
        base.split('/').collect()
    };
    for seg in href.split('/') {
        match seg {
            "" | "." => {}
            ".." => {
                parts.pop();
            }
            s => parts.push(s),
        }
    }
    parts.join("/")
}

// --- the two hand-rolled XML readers ---------------------------------------
//
// Both only ever look at `container.xml` and the OPF, which are machine-written
// and must be valid XML for any reader to open the book at all.

/// Every `<name ...>` tag in the document, as raw tag text.
fn tags_named(xml: &str, name: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut rest = xml;
    while let Some(i) = rest.find('<') {
        rest = &rest[i + 1..];
        let Some(end) = rest.find('>') else { break };
        let tag = &rest[..end];
        let tag_name = tag
            .split([' ', '\t', '\n', '\r', '/'])
            .next()
            .unwrap_or("")
            .rsplit(':')
            .next()
            .unwrap_or("");
        if tag_name.eq_ignore_ascii_case(name) {
            out.push(tag.to_string());
        }
        rest = &rest[end + 1..];
    }
    out
}

fn attr_of(xml: &str, tag_name: &str, attr_name: &str) -> Option<String> {
    tags_named(xml, tag_name)
        .iter()
        .find_map(|t| attr(t, attr_name))
}

/// One attribute out of a raw tag, single or double quoted.
fn attr(tag: &str, name: &str) -> Option<String> {
    let mut rest = tag;
    while let Some(i) = rest.to_ascii_lowercase().find(&name.to_ascii_lowercase()) {
        let before_ok = i == 0
            || rest[..i]
                .chars()
                .next_back()
                .is_some_and(|c| c.is_whitespace());
        let after = rest[i + name.len()..].trim_start();
        if before_ok && let Some(after) = after.strip_prefix('=') {
            let after = after.trim_start();
            let quote = after.chars().next()?;
            if quote == '"' || quote == '\'' {
                let body = &after[1..];
                let end = body.find(quote)?;
                return Some(decode_entities(&body[..end]));
            }
        }
        rest = &rest[i + name.len()..];
    }
    None
}

// --- markup stripping -------------------------------------------------------

/// Tags whose *contents* are not text: metadata, code, and ruby readings.
const DROPPED_CONTENT: &[&str] = &["head", "script", "style", "rt", "rp"];

/// Tags that end a line. A Japanese novel's line breaks are `<p>` and `<br/>`;
/// the rest are here so a book built out of `<div>`s does not come back as one
/// unbroken paragraph.
const BREAKS: &[&str] = &[
    "p",
    "br",
    "div",
    "li",
    "tr",
    "hr",
    "blockquote",
    "section",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
];

pub fn strip_markup(html: &str) -> String {
    let mut out = String::with_capacity(html.len() / 2);
    let mut rest = html;

    while let Some(i) = rest.find('<') {
        push_text(&mut out, &rest[..i]);
        let after = &rest[i..];

        if let Some(body) = after.strip_prefix("<!--") {
            rest = body.find("-->").map_or("", |e| &body[e + 3..]);
            continue;
        }
        if after.starts_with("<!") || after.starts_with("<?") {
            rest = after.find('>').map_or("", |e| &after[e + 1..]);
            continue;
        }
        let Some(end) = after.find('>') else {
            break;
        };
        let tag = &after[1..end];
        rest = &after[end + 1..];

        let closing = tag.starts_with('/');
        let self_closing = tag.ends_with('/');
        let name = tag
            .trim_start_matches('/')
            .split([' ', '\t', '\n', '\r', '/'])
            .next()
            .unwrap_or("")
            .rsplit(':')
            .next()
            .unwrap_or("")
            .to_ascii_lowercase();

        if !closing
            && !self_closing
            && DROPPED_CONTENT.contains(&name.as_str())
            && let Some(skipped) = skip_to_close(rest, &name)
        {
            rest = skipped;
            continue;
        }
        if BREAKS.contains(&name.as_str()) {
            out.push('\n');
        }
    }
    push_text(&mut out, rest);
    tidy(&out)
}

/// Everything after the matching close tag, or `None` if it never closes —
/// in which case the tag is treated as an ordinary one rather than eating the
/// rest of the document.
fn skip_to_close<'a>(rest: &'a str, name: &str) -> Option<&'a str> {
    let lower = rest.to_ascii_lowercase();
    let needle = format!("</{name}");
    let at = lower.find(&needle)?;
    let after = &rest[at..];
    after.find('>').map(|e| &rest[at + e + 1..])
}

fn push_text(out: &mut String, raw: &str) {
    if !raw.is_empty() {
        out.push_str(&decode_entities(raw));
    }
}

fn decode_entities(raw: &str) -> String {
    if !raw.contains('&') {
        return raw.to_string();
    }
    let mut out = String::with_capacity(raw.len());
    let mut rest = raw;
    while let Some(i) = rest.find('&') {
        out.push_str(&rest[..i]);
        let after = &rest[i + 1..];
        // An entity is short; a bare `&` in the text must not swallow the line.
        let end = after.chars().take(12).position(|c| c == ';');
        match end.map(|e| (&after[..e], &after[e + 1..])) {
            Some((body, tail)) => {
                match named_entity(body) {
                    Some(c) => out.push(c),
                    None => {
                        out.push('&');
                        out.push_str(body);
                        out.push(';');
                    }
                }
                rest = tail;
            }
            None => {
                out.push('&');
                rest = after;
            }
        }
    }
    out.push_str(rest);
    out
}

fn named_entity(body: &str) -> Option<char> {
    match body {
        "amp" => Some('&'),
        "lt" => Some('<'),
        "gt" => Some('>'),
        "quot" => Some('"'),
        "apos" => Some('\''),
        "nbsp" => Some(' '),
        _ => {
            let n = match body.strip_prefix("#x").or_else(|| body.strip_prefix("#X")) {
                Some(hex) => u32::from_str_radix(hex, 16).ok()?,
                None => body.strip_prefix('#')?.parse().ok()?,
            };
            char::from_u32(n)
        }
    }
}

/// Collapse the whitespace the markup left behind: spaces to one, every run of
/// line breaks to one. Newlines are kept because the tokenizer segments on
/// them; blank lines are not, because an open and a close tag both end a line
/// and the gap between two paragraphs is not information.
fn tidy(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for line in s.lines() {
        let mut trimmed = String::with_capacity(line.len());
        let mut last_space = false;
        for c in line.trim().chars() {
            let space = c == ' ' || c == '\t';
            if space && last_space {
                continue;
            }
            trimmed.push(if space { ' ' } else { c });
            last_space = space;
        }
        if trimmed.is_empty() {
            continue;
        }
        if !out.is_empty() {
            out.push('\n');
        }
        out.push_str(&trimmed);
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ruby_readings_are_not_text() {
        let got = strip_markup("<p><ruby>漢字<rp>(</rp><rt>かんじ</rt><rp>)</rp></ruby>を読む</p>");
        assert_eq!(got, "漢字を読む");
    }

    #[test]
    fn paragraphs_become_lines() {
        let got = strip_markup("<p>一行目</p><p>二行目</p>");
        assert_eq!(got, "一行目\n二行目");
    }

    #[test]
    fn entities_decode_and_a_bare_ampersand_survives() {
        assert_eq!(strip_markup("<p>&#x3042;&amp;&#12356;</p>"), "あ&い");
        assert_eq!(strip_markup("<p>Tom & Jerry</p>"), "Tom & Jerry");
    }

    #[test]
    fn scripts_and_heads_are_dropped_whole() {
        let got = strip_markup("<head><title>x</title></head><body><p>本文</p></body>");
        assert_eq!(got, "本文");
    }

    #[test]
    fn an_unclosed_dropped_tag_does_not_eat_the_document() {
        assert_eq!(strip_markup("<p>前<rt>後"), "前後");
    }

    #[test]
    fn hrefs_resolve_against_the_opf_directory() {
        assert_eq!(
            resolve("OEBPS/text", "../images/a.xhtml"),
            "OEBPS/images/a.xhtml"
        );
        assert_eq!(resolve("", "chap1.xhtml#top"), "chap1.xhtml");
    }

    #[test]
    fn attributes_read_under_either_quote_and_never_off_a_prefix() {
        let tag = r#"item id='x1' href="a.xhtml" data-href="no""#;
        assert_eq!(attr(tag, "href").as_deref(), Some("a.xhtml"));
        assert_eq!(attr(tag, "id").as_deref(), Some("x1"));
    }
}
